HEH-UI-93: Added spinner and interceptor for it
MaksimViarenich/HEH_UI pull request #105
Opened 2021-02-11 16:03 UTC by akhaulin

2021-02-11 21:57 UTC, MaksimViarenich requested changes

2021-02-11 21:57 UTC, MaksimViarenich commented on heh-ui/src/app/components/layouts/home-layout/home-layout.component.scss
> +  left:       0;
Что за чудный code style?)

2021-02-11 21:57 UTC, MaksimViarenich commented on heh-ui/src/app/services/spinner-service/spinner-interceptor.ts
> +
удалить эту строчку

2021-02-11 22:14 UTC, akhaulin commented on heh-ui/src/app/components/layouts/home-layout/home-layout.component.scss
> +  left:       0;
это tint чтобы не были доступны элементы пока идет загрузка страницы

2021-02-11 22:35 UTC, akhaulin commented on heh-ui/src/app/services/spinner-service/spinner-interceptor.ts
> +
fixed

2021-02-12 09:03 UTC, MaksimViarenich approved these changes

2021-02-12 09:03 UTC, merged